language: rust

rust:
  - stable
  - nightly

jobs:
  include:
    - name: build and test
      script:
        - cargo build --release --all --verbose
        - cargo test --release --all --verbose
    
    - name: fossa
      before_script:
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/fc60c6631a5d372d5a45fea35e31665b338f260d/install.sh | sudo bash"
      script:
        - fossa init
        - fossa analyze --server-scan
        - fossa test
