# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-near
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
    
    - name: Build contract
      run: |
        # Run the build script to create the WASM
        ./build.sh
        echo "✅ Contract built successfully!"
        echo "WASM checksum: $(sha256sum target/near/linkdrop.wasm)"
        echo "ABI checksum: $(sha256sum target/near/linkdrop_abi.json)"
    
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linkdrop-contract
        path: |
          target/near/linkdrop.wasm
          target/near/linkdrop_abi.json
        retention-days: 30
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
