# This workflow builds the NEAR smart contract and runs both unit and integration tests using Rust
# The tests use near-sandbox and near-api for comprehensive testing

name: Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install cargo-near
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
    
    - name: Check code formatting
      run: |
        echo "🎨 Checking code formatting..."
        cargo fmt --all -- --check
        echo "✅ Code formatting check passed!"
    
    - name: Build contract
      run: |
        echo "🔨 Building contract with cargo-near..."
        # Build the WASM contract first (required for clippy and integration tests)
        cargo near build non-reproducible-wasm
        echo "✅ Contract built successfully!"
        echo "WASM location: $(ls -la target/near/linkdrop.wasm)"
        echo "WASM checksum: $(sha256sum target/near/linkdrop.wasm)"
        if [ -f target/near/linkdrop_abi.json ]; then
          echo "ABI checksum: $(sha256sum target/near/linkdrop_abi.json)"
        fi
    
    - name: Run clippy lints
      run: |
        echo "📋 Running clippy lints..."
        # Allow deprecated warnings for UnorderedMap (migration would break existing contracts)
        # Allow match_like_matches_macro and useless_conversion warnings in existing code
        cargo clippy --all-targets --all-features -- \
          -D warnings \
          -A deprecated \
          -A clippy::match_like_matches_macro \
          -A clippy::useless_conversion
        echo "✅ Clippy checks passed!"
    
    - name: Run tests
      run: |
        echo "🧪 Running all tests (unit + integration)..."
        cargo test --verbose
        echo "✅ All tests passed!"
    
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linkdrop-contract
        path: |
          target/near/linkdrop.wasm
          target/near/linkdrop_abi.json
        retention-days: 30
