# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-near
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
    
    - name: Build contract and verify reproducibility
      run: |
        # Save the original WASM for comparison
        cp res/linkdrop.wasm res/linkdrop.wasm.original
        
        # Run the build script
        ./build.sh
        
        # Compare the built WASM with the committed one
        if ! cmp -s res/linkdrop.wasm res/linkdrop.wasm.original; then
          echo "❌ ERROR: Built WASM differs from committed WASM!"
          echo "The WASM file in res/linkdrop.wasm must be built using ./build.sh"
          echo "Please run ./build.sh locally and commit the resulting res/linkdrop.wasm"
          echo ""
          echo "Checksums:"
          echo "Original: $(sha256sum res/linkdrop.wasm.original)"
          echo "Built:    $(sha256sum res/linkdrop.wasm)"
          exit 1
        else
          echo "✅ WASM reproducibility check passed!"
          echo "Checksum: $(sha256sum res/linkdrop.wasm)"
        fi
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
